Lab 4 Deliverables/NTUFoodie/NTUFoodie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from NTUFoodieApp.forms import CreateUserForm
from django.conf.urls.static import static
from django.conf import settings
from NTUFoodieApp.models import *
from django.contrib.auth.models import Group
from NTUFoodieApp.decorators import unauthenticated_user
from NTUFoodieApp import views
from django.conf.urls import handler404, handler500



def defaultHome(request):
    return render(request, "NTUFoodieApp/home.html")

@unauthenticated_user
def registerPage(request):
        form = CreateUserForm()
        canteens = Canteen.objects.all()
        if request.method == "POST":
            form = CreateUserForm(request.POST)
            if form.is_valid():
                
                role = request.POST.get('role')
                firstName = request.POST.get('firstName')
                lastName = request.POST.get('lastName')
                user = form.save()
                username = form.cleaned_data.get('username')
                email = form.cleaned_data.get('email')
                
                if(role == "consumer"):
                    group = Group.objects.get(name="consumer")
                    user.groups.add(group)
                    Consumer.objects.create(
                        user = user,
                        firstName = firstName,
                        lastName = lastName,
                        email = email
                        )
                else:
                    canteenName = request.POST.get('canteenName')
                    storeName = request.POST.get('storeName')
                    canteen = Canteen.objects.get(location__canteenName=canteenName)
                        
                    store = Store.objects.create(
                        storeName = storeName,
                        canteen = canteen
                    )
                    
                    group = Group.objects.get(name="storeowner")
                    user.groups.add(group)
                    
                    StoreOwner.objects.create(
                        user = user,
                        store = store,
                        firstName = firstName,
                        lastName = lastName,
                        email = email 
                    )
        
                    #create store and canteen if not exist
        
                messages.success(request, "Account was created for " + username)
                return redirect('login')
                
        context = {'form': form, "canteens" : canteens}
        
        return render(request, "NTUFoodieApp/register.html", context)

def loginPage(request):
    if request.user.is_authenticated:
        user = request.user
        role = user.groups.first()
        if str(role) == "consumer":
            return redirect('cHome')
        elif str(role) == "storeowner":
            return redirect('soHome')
        else:
            return redirect('aHome')
    else: 
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')

            # Check if the user exists
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                messages.error(request, 'Invalid username or password.')
                return render(request, "NTUFoodieApp/login.html")

            # Check if the user is banned
            if not user.is_active and BannedUser.objects.filter(user=user, isBanned=True).exists():
                messages.error(request, "Your account has been banned. Please contact support.")
                return render(request, "NTUFoodieApp/login.html")

            # Authenticate the user
            user = authenticate(request, username=username, password=password)

            if user is not None:
                role = user.groups.first()
                if str(role) == "consumer":
                    login(request, user)
                    return redirect('cHome')  
                elif str(role) == "storeowner":
                    login(request, user)
                    return redirect('soHome')
                else:
                    login(request, user)
                    return redirect('aHome')
            else:
                messages.error(request, 'Invalid username or password.') 
                return render(request, "NTUFoodieApp/login.html")

        return render(request, "NTUFoodieApp/login.html")



def logoutUser(request):
    logout(request)
    return redirect('login')


urlpatterns = [
    path("admin/dashboard/", admin.site.urls),
    path("admin/home/", views.adminHome, name = "aHome" ),
    path("admin/notification/<str:pk_id>", views.anotifications, name="aNotification"),
    path("admin/flaggedReview/", views.processReview, name="flaggedReview"),
    path("admin/flaggedReview/markProcessed/<str:pk_id>", views.markAsProcessed, name="markProcessed"),
    path("admin/flaggedReview/deleteReview/<str:pk_id>", views.adminDeleteReview, name="adminDeleteReview"),
    path("admin/consumerList/", views.consumerList, name="consumerList"),
    path("admin/consumerList/banUser/<str:pk_id>", views.adminBanUser, name="banUser"),
    path("", defaultHome, name = "defaultHome"),
    path("register/", registerPage, name = "register"),
    path("login/", loginPage, name = "login"),
    path("logout/",logoutUser, name = "logout"),
    path("consumer/", include("NTUFoodieApp.consumer_urls")),
    path("storeowner/", include("NTUFoodieApp.storeowner_urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin.site.index_title = "NTUFOODIE"
admin.site.site_header = "NTUFOODIE Admin"

handler404 = 'NTUFoodieApp.views.errorView'
handler500 = 'NTUFoodieApp.views.serverErrorView'

Lab 4 Deliverables/NTUFoodie/NTUFoodieApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
import geocoder
from django.conf import settings

# Create your models here.

class Consumer(models.Model):
    user = models.OneToOneField(User, null = True, on_delete=models.CASCADE)
    firstName = models.CharField(max_length = 200, null = True)
    lastName = models.CharField(max_length = 200, null = True)
    email = models.CharField(max_length = 200, null = True)
    profilePic = models.ImageField(default = "default_profile.png", null=True, blank=True)
    dateCreated = models.DateTimeField(auto_now_add=True, null = True)
    
    def __str__(self):
        return self.firstName + " " + self.lastName 
    
class Location(models.Model):
    canteenName = models.CharField(max_length = 200, null = True)
    address = models.TextField(blank=True, null=True, unique=True)
    lat = models.FloatField(blank=True, null=True)
    long = models.FloatField(blank=True, null=True)
    
    def __str__(self):
        return str(self.address)
    
    def save(self, *args, **kwargs):
        g = geocoder.mapbox(self.address, key = settings.MAPBOX_ACCESS_TOKEN)
        g = g.latlng
        self.lat = g[0]
        self.long = g[1]
        
        return super(Location, self).save(*args, **kwargs)   
    
class Canteen(models.Model):
    location = models.ForeignKey(Location, null = True, on_delete=models.CASCADE)
    canteenPic = models.ImageField(default = "default_canteen.png", null=True, blank=True)
    dateCreated = models.DateTimeField(auto_now_add=True, null = True)

    def __str__(self):
        return self.location.canteenName

class Store(models.Model): 
    storeName = models.CharField(max_length = 200, null = True)
    canteen = models.ForeignKey(Canteen, null = True, on_delete=models.CASCADE)
    storePic = models.ImageField(default = "default_store.png", null=True, blank=True)
    dateCreated = models.DateTimeField(auto_now_add=True, null = True)
    
    def __str__(self):
        return self.storeName + " @ " + self.canteen.location.canteenName
    
class StoreOwner(models.Model):
    user = models.OneToOneField(User, null = True, on_delete=models.CASCADE)
    store = models.OneToOneField(Store, null = True, on_delete=models.CASCADE)
    firstName = models.CharField(max_length = 200, null = True)
    lastName = models.CharField(max_length = 200, null = True)
    email = models.CharField(max_length = 200, null = True)
    profilePic = models.ImageField(default = "default_profile.png", null=True, blank=True)
    dateCreated = models.DateTimeField(auto_now_add=True, null = True)
    
    def __str__(self):
        return self.firstName + " " + self.lastName 
    
class Food(models.Model):
    store = models.ForeignKey(Store, null = True, on_delete=models.CASCADE)
    foodName = models.CharField(max_length = 200, null = True)
    price = models.FloatField(null = True)
    type = models.CharField(max_length = 50, null = True)
    cuisine = models.CharField(max_length = 50, null = True)
    description = models.TextField(max_length = 1000, null = True)
    rating = models.FloatField(null = True)
    image = models.ImageField(default="comingsoon.jpg", null = True, blank = True)
    isDiscounted = models.BooleanField(default=False)
    discountRate = models.IntegerField(null = True, blank = True)
    discountedPrice = models.FloatField(null = True, blank = True)
    dateCreated = models.DateTimeField(auto_now_add=True, null = True)
    
    def __str__(self):
        return self.foodName + " from " + self.store.storeName + " @ " + self.store.canteen.location.canteenName
    
    def save(self, *args, **kwargs):
        if self.isDiscounted and self.discountRate:
            self.discountedPrice = self.price * ((100 - self.discountRate) / 100)
        else:
            self.discountedPrice = None  # No discount
        
        super(Food, self).save(*args, **kwargs)


class Review(models.Model):
    user = models.ForeignKey(User, null = True, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, null = True, on_delete=models.CASCADE, related_name = 'reviews')
    rating = models.FloatField(null = True)
    description = models.TextField(max_length = 1000, null = True)
    image = models.ImageField(null = True, blank = True, default="NTUFOODIElogo.png")
    dateCreated = models.DateTimeField(auto_now_add=True, null = True)
    
    def __str__(self):
        return self.user.consumer.firstName + " " + self.user.consumer.lastName + " , " + self.food.foodName + " from " + self.food.store.storeName
    
    
class FlaggedReview(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    flaggedBy = models.ForeignKey(User, on_delete=models.CASCADE)
    reason = models.TextField(max_length=500, null=True)
    isProcessed = models.BooleanField(default=False)
    dateFlagged = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Review {self.review} flagged by {self.flaggedBy}"

class Notification(models.Model):
    title = models.TextField(max_length = 100, null = True)
    description = models.TextField(max_length = 1000, null = True)
    viewed = models.BooleanField(default = False, null = True)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    dateCreated = models.DateTimeField(auto_now_add=True, null = True)

    def __str__(self):
        return f"Notification for {self.user.username}. Title: {self.title}" 
    
class BannedUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bannedOn = models.DateTimeField(auto_now_add=True)
    isBanned = models.BooleanField(default=True)

    def __str__(self):
        return f"Banned user: {self.user.username}." 


#Welcome Message 
@receiver(post_save, sender=User)
def create_welcome_message(sender, **kwargs):
    if kwargs.get('created', False):
        Notification.objects.create(user=kwargs.get('instance'),
                                    title = "Welcome to NTUFOODIE!",
                                    description = "Thanks for signing up Foodies! Enjoy the good food in NTU!")
        
# @receiver(post_save, sender=BannedUser)
# def deactivate_user_on_ban(sender, instance, created, **kwargs):
#     user = instance.user
#     if instance.is_banned:
#         user.is_active = False
#         user.save()
#     else:
#         user.is_active = True
#         user.save()
    
#Notification when a review is flagged
#@receiver(post_save, sender=FlaggedReview)
#def notify_admin_on_flagged_review(sender, instance, created, **kwargs):
#    if created:
#        Notification.objects.create(
#            user=User.objects.get(is_superuser=True),  
#            title="Review Flagged",
#            description=f"A review by {instance.review.user.username} has been flagged for: {instance.reason}"
#        )
        
#Notifying when consumer's review is deleted
#@receiver(models.signals.pre_delete, sender=Review)
#def notify_user_on_review_deletion(sender, instance, **kwargs):
#    Notification.objects.create(
#        user=instance.user,
#        title="Review Deleted",
#        description=f"Your review for {instance.food.foodName} has been deleted by an admin."
#    )

Lab 4 Deliverables/NTUFoodie/NTUFoodieApp/forms.py
from django.forms import ModelForm
from .models import Review
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *

class ConsumerForm(ModelForm):
    class Meta:
        model = Consumer
        fields = ['firstName', 'lastName', 'profilePic']
        widgets = {
            'profilePic': forms.FileInput()
        }
        
class StoreOwnerForm(ModelForm):
    class Meta:
        model = StoreOwner
        fields = ['firstName', 'lastName', 'profilePic']
        widgets = {
            'profilePic': forms.FileInput()
        }

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'description', 'image']
        
class FlagReviewForm(ModelForm):
    class Meta:
        model = FlaggedReview
        fields = ['reason']
        
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
from django import forms
from .models import Food

class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ['foodName', 'price', 'type', 'cuisine', 'description', 'isDiscounted', 'discountRate', 'image']

    def __init__(self, *args, **kwargs):
        super(FoodForm, self).__init__(*args, **kwargs)
        # Set choices for 'type' and 'cuisine' dynamically
        self.fields['type'].widget = forms.Select(
            choices=[(type_choice, type_choice) for type_choice in Food.objects.values_list('type', flat=True).distinct()]
        )
        self.fields['cuisine'].widget = forms.Select(
            choices=[(cuisine_choice, cuisine_choice) for cuisine_choice in Food.objects.values_list('cuisine', flat=True).distinct()]
        )
        
    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price is not None and price < 0:
            raise forms.ValidationError('Price cannot be negative.')
        return price

    def clean(self):
        cleaned_data = super().clean()
        is_discounted = cleaned_data.get('isDiscounted')
        discount_rate = cleaned_data.get('discountRate')

        # Validate discountRate only if isDiscounted is True
        if is_discounted:
            if discount_rate is None:
                self.add_error('discountRate', 'Please provide a discount rate when the item is discounted.')
            else:
                if discount_rate < 0:
                    self.add_error('discountRate', 'Discount rate cannot be negative.')
                elif discount_rate >= 100:
                    self.add_error('discountRate', 'Discount rate must be less than 100%.')
        else:
            # If the item is not discounted, ensure discountRate is None
            cleaned_data['discountRate'] = None
        return cleaned_data

Lab 4 Deliverables/NTUFoodie/NTUFoodieApp/templates/NTUFoodieApp/listingdetail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Listing Detail</title>
  <link rel="icon" type="image/png" href="{% static 'images/logo.jpeg' %}">
  <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" 
        integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" 
        crossorigin="anonymous" referrerpolicy="no-referrer" />
  <style>
  body {
  background-color: #f8f9fa;
  font-family: 'Inter', sans-serif !important;
  }

  .alert-success {
  background-color: #d4edda; /* Light green background */
  color: #155724; /* Dark green text */
  border: 1px solid #c3e6cb; /* Light green border */
  border-radius: 5px;
  margin-bottom: 30px;
  font-family: 'Inter', sans-serif;
  font-size: 1.1rem;
  font-weight: 500;
  position: relative;
  }

  .custom-line {
  border: none; /* Remove default border */
  height: 2px; /* Set line thickness */
  background-color: #dc3545; /* Line color */
  margin: 20px 0; /* Space around the line */
  opacity: 0.8; /* Optional: Adjust opacity */
  }

  .header-container {
  display: flex;
  align-items: center;
  justify-content: space-between; /* Ensures space between the title and delete icon */
  }

  .header-container h3 {
  margin: 0; /* Remove default margin for alignment */
  }

  .delete-icon {
  font-size: 1.9rem;
  color: #dc3545;
  cursor: pointer;
  position: static; /* Remove absolute positioning */
  }

  .delete-icon:hover {
  color: #c82333;
  }

  .food-details-card {
  font-family: 'Inter', sans-serif;
  background-color: #fff;
  padding: 30px;
  margin-top: 30px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .food-details-card h3 {
  font-family: 'Inter', sans-serif;
  font-size: 2.3rem;
  font-weight: 600;
  }

  .food-image {
  width: 100%;
  height: 250px;
  object-fit: cover;
  border: 2px solid #ddd;
  border-radius: 30px;
  margin: 20px auto;
  }

  .store-details{
  font-family: 'Inter',sans-serif;
  font-weight: 600;
  font-size: 1.4rem;
  display: flex;
  padding-top: 5px;
  padding-left: 10px;
  }

  .food-name {
  font-family: 'Inter', sans-serif;
  font-weight: 500;
  font-size: 1.4rem;
  text-decoration: underline;
  display: flex;
  flex-direction: column;
  align-items: flex-start; 
  padding-bottom: 15px;
  padding-left: 10px;
  border-bottom-left-radius: 30px;
  border-bottom-right-radius: 30px;

  }

  .food-details {
  margin-top: 15px; /* Adjust spacing as needed */
  font-family: 'Inter', sans-serif;
  }

  .food-details div {
  margin-bottom: 5px; /* Space between different details */
  font-weight: 500;
  }

  .food-details label {
  font-weight: bold; /* Bold labels for clarity */
  }

  .food-details span {
  margin-left: 5px; /* Space between label and value */
  color: #757575; /* Subtle color for values */
  }

  .custom-line {
  border: none; /* Remove default border */
  height: 2px; /* Set line thickness */
  background-color: #dc3545; /* Line color */
  margin: 20px 0; /* Space around the line */
  opacity: 0.8; /* Optional: Adjust opacity */
  }     


  .form-group label {
  font-family: 'Inter', sans-serif;
  font-size: 1.2rem;
  font-weight: 600;
  }

    /* General styling for all input fields */
  input[type="text"], input[type="number"], input[type="email"], textarea, select {
  border-radius: 1rem;  /* Rounded corners */
  border: 1px solid #ccc;
  padding: 0.5rem 1rem;
  width: 100%;
  box-sizing: border-box;
  transition: box-shadow 0.3s ease; /* Smooth shadow transition */
  }

  /* Red shadow effect on focus */
  input[type="text"]:focus, input[type="number"]:focus, input[type="email"]:focus,
  textarea:focus, select:focus {
  outline: none;
  border-color: #dc3545;
  box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.25);
  }

  .form-control:focus {
  border-color: #dc3545;
  box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.25);
  }

  .form-control {
    border-radius: 1rem; /* Match the input styling */
    padding: 10px; /* Add padding to the input */
    border: 1px solid #ccc;
    box-sizing: border-box; /* Include padding in width and height calculations */
    height: auto; /* Ensure height adjusts automatically */
    min-height: 2.5rem; /* Set a minimum height to accommodate padding */
}

  .btn-update {
  font-family: "Inter", sans-serif;
  font-weight: 500;
  border-radius: 2rem;
  padding: 1rem 2rem;
  background-color: #D63531;
  border-color: #D63531;
  color: white;
  margin-top: 30px;
  }

  .btn-update:hover {
  background-color: #9e0a2c;
  border-color: 20px#9e0a2c;
  color: white !important;
  }

  .button-wrapper {
  margin-top: 10px;
  display: flex;
  justify-content: center;
  }

  textarea {
  padding: 10px; /* Adjust as needed */
  border: 1px solid #ced4da; /* Keep the border for consistency */
  border-radius: 5px; /* Optional: maintain the border radius */
  width: 100%; /* Ensure it takes the full width */
  }

  .rating-display .rating-output {
  font-weight: bold;
  color: #dc3545;
  }

  .discounted-price {
  color: red !important;
  font-weight: bold;
  }
  .original-price {
  text-decoration: line-through;
  }
  #discountRateField {
  display: none; /* Initially hidden */
  }
  </style>
</head>
<body>
  <div class="container">
    <div class="row justify-content-center mt-3">
      <div class="col-md-8">
        <div class="back-button"> 
          <a href="{% url 'soHome' %}" class="btn btn-link">
            <i class="fas fa-arrow-left"></i> Back
          </a>
        </div>

        <div class="container">
          {% if messages %}
            <div class="mt-3">
              {% for message in messages %}
                {% if message.tags == 'error' %}
                  <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {% else %}
                  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {% endif %}
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
              {% endfor %}
            </div>
          {% endif %}
        </div>
        

        <div class="food-details-card">
          <div class="header-container">
              <h3>Update Listing</h3>
            <!-- Delete button as an 'x' icon -->
            <a href="#" class="delete-icon" title="Delete Listing" data-toggle="modal" data-target="#deleteListingModal">
              <i class="fas fa-times"></i>
            </a>
          </div>

          <!-- Review Image or Default Image -->
          {% if food.image %}
          <img src="{{ food.image.url }}" class="food-image">
          {% else %}
          <img src="{% static 'images/comingsoon.jpg' %}" class="food-image" alt="Default Food Image">
          {% endif %}

          <div class="store-details">{{ food.store.storeName }} @ {{ food.store.canteen.location.canteenName }}</div>
          <div class="food-name">{{ food.foodName }}</div>

          <hr class="custom-line">

          <div class="food-details">
            <div class="food-rating">
              {% if food.rating %}
              <label>Your Rating:</label> {{ food.rating|floatformat:1 }} <i class="fas fa-star text-warning"></i> 
              {% else %}
              <label>Your Rating:</label>  NA
              {% endif %}
            </div>

            <div class="food-price">
              <label>Price: </label>
              {% if food.isDiscounted and food.discountRate %}
                <span class="original-price">SGD {{ food.price|floatformat:2 }}</span> 
                <span class="discounted-price">SGD {{ food.discountedPrice|floatformat:2 }}</span>
              {% else %}
                SGD {{ food.price|floatformat:2 }}
              {% endif %}
            </div>
                  <div class="form-group">
                  <label for="type">Type:</label>
                  <span class="type">{{ food.type }}</span> 
                </div>
                <div class="form-group">
                  <label for="cuisine">Cuisine:</label>
                  <span class="cuisine">{{ food.cuisine }}</span> 
                </div>

            <div class="food-description">
              <label>Description:</label> {{ food.description }}
            </div>
          </div>

          <hr class="custom-line">

          <div class="review-form">
            <!-- Form to update review -->
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
            
              <div class="form-group">
                <label for="foodName">Food Name:</label>
                <div>{{ form.foodName }}</div>
            </div>
            
            <div class="form-group">
                {{ form.price.label_tag }}
                <div>{{ form.price }}</div>
                {% if form.price.errors %}
                    <div class="text-danger">
                        {{ form.price.errors }}
                    </div>
                {% endif %}
            </div>
            
            <div class="form-group">
              <label for="type">Type:</label>
              <select class="form-control" id="type" name="type">
                  <option value="">-</option>
                  {% for type in types %}
                      <option value="{{ type }}" {% if type == food.type %}selected{% endif %}>{{ type }}</option>
                  {% endfor %}
              </select>
          </div>
          
          <div class="form-group">
              <label for="cuisine">Cuisine:</label>
              <select class="form-control" id="cuisine" name="cuisine">
                  <option value="">-</option>
                  {% for cuisine in cuisines %}
                      <option value="{{ cuisine }}" {% if cuisine == food.cuisine %}selected{% endif %}>{{ cuisine }}</option>
                  {% endfor %}
              </select>
          </div>
          

              <div class="form-group">
                <label for="description">Description:</label>
                {{ form.description }}
              </div>

              <div class="form-group">
                <label for="isDiscounted">On Discount:</label>
                {{ form.isDiscounted }}
              </div>
            
        <!-- Discount Rate Field -->
        <div class="form-group" id="discount-rate-field">
          <label for="{{ form.discountRate.id_for_label }}" class="custom-label-class">Discount Rate:</label>
          {{ form.discountRate }}
          {% if form.discountRate.errors %}
              <div class="text-danger">
                  {{ form.discountRate.errors }}
              </div>
          {% endif %}
      </div>

      <!-- Image Field -->
      <div class="form-group">
          {{ form.image.label_tag }}
          {{ form.image }}
          {% if form.image.errors %}
              <div class="text-danger">
                  {{ form.image.errors }}
              </div>
          {% endif %}
      </div>
            
              <div class="form-group">
                <button type="submit" class="btn btn-update">Update Listing</button>
              </div>
            </form>
            
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Delete Confirmation Modal -->
  <div class="modal fade" id="deleteListingModal" tabindex="-1" role="dialog" aria-labelledby="deleteListingModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteReviewModalLabel">Confirm Deletion</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this listing?</p>
        </div>
        <div class="modal-footer">
          <form method="POST" action="{% url 'deleteListing' food.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  <script>
    $(document).ready(function(){
      // Function to show/hide the discount rate field
      function toggleDiscountRate() {
          if ($('#id_isDiscounted').is(':checked')) {
              $('#discount-rate-field').show();
          } else {
              $('#discount-rate-field').hide();
          }
      }
  
      // Initially call the function to set the correct visibility
      toggleDiscountRate();
  
      // Bind the function to the change event of the isDiscounted checkbox
      $('#id_isDiscounted').change(function(){
          toggleDiscountRate();
      });
  });
  </script>
  
  
</body>
</html>